docs_dir: docs/book
site_dir: docs/html
nav:
    - index.md
    - Intro: intro.md
    - Reference:
        - "Theory of Operation": theory-of-operation.md
        - Configuration: configuration.md
        - "Escaping HTML": escaping-html.md
        - "Escaping HTML Attributes": escaping-html-attributes.md
        - "Escaping Javascript": escaping-javascript.md
        - "Escaping CSS": escaping-css.md
        - "Escaping URLs": escaping-url.md
site_name: laminas-escaper
site_description: laminas-escaper
repo_url: 'https://github.com/laminas/laminas-escaper'
